#!/usr/bin/env bash

sed -i "s/listen [::]:8080 default_server;/listen [::]:80 default_server/" /etc/nginx/sites-enabled/default
sed -i "s/listen 8080 default_server;/listen 80 default_server/" /etc/nginx/sites-enabled/default
sed -i "s/ ipv4only=on//" /etc/nginx/sites-available/default
nginx -t && nginx -s reload || echo "nginx is not running"

