#!/usr/bin/env bash
# Configures an Nginx server to listen on port 80.
sed -i "s/8080/80/g" /etc/nginx/sites-enabled/default

# Restart Nginx service
service nginx restart

# Kill Nginx process to force reload
kill -9 "$(cat /run/nginx.pid)"
