#!/usr/bin/env bash
# Configure Nginx server to listen on port 80

# Creates a symbolic link Nginx file and enables sites dir
In -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart Nginx
service nginx restart

# Terminate the first nginx
kill "$(pgrep 'nginx' | head -1)"
