#!/usr/bin/env bash
# This script displays formatted information about users in /etc/passwd using a while loop and IFS.

while IFS=: read -r username _ uid gid gecos home shell; do
    echo "The user $username is part of the $gid gang, lives in $home and rides $shell."
    echo "USER ID's place is protected by the passcode, more info about the user here: $gecos"
done < /etc/passwd
