#!/usr/bin/env bash
# client configuration for ssh

Host *
	PasswordAuthentication no
	IdentityFile ~/.ssh/school
	SendEnv LANG LC_*
	HashKnownHosts yes
	GSSAPIAuthentication yes
	GSSAPIDelegateCredentials no
